# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='beta',
        ),
    ]
